using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LibVLCSharp.Core.Generator
{
    /// <summary>
    /// Incremental source generator that emits public PascalCase delegate twins of the raw
    /// snake_case <c>libvlc_*</c> callback typedefs in the generated interop file.
    /// <para>
    /// e.g. <c>libvlc_media_open_cb</c> =&gt; <c>public delegate int MediaOpenCallback(...)</c>.
    /// The signature (return type, parameters, attributes, <c>unsafe</c> modifier) is copied
    /// verbatim, so the alias is signature-identical to its interop twin. Because C# delegate types
    /// are never assignable across type identity, the managed wrappers convert an alias handler to
    /// its interop twin at the P/Invoke boundary (via a method-group delegate). Unlike the enum
    /// aliases, these are friendlier in <em>name</em> only — the parameters still expose interop
    /// pointer types.
    /// </para>
    /// </summary>
    [Generator(Microsoft.CodeAnalysis.LanguageNames.CSharp)]
    public sealed class DelegateAliasGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Each matching interop delegate becomes a self-contained text block (strings are
            // value-equatable, so the incremental pipeline caches correctly).
            var blocks = context.SyntaxProvider.CreateSyntaxProvider(
                    predicate: static (node, _) =>
                        node is DelegateDeclarationSyntax d &&
                        d.Identifier.Text.StartsWith("libvlc_", StringComparison.Ordinal),
                    transform: static (ctx, _) => RenderDelegate((DelegateDeclarationSyntax)ctx.Node))
                .Collect();

            context.RegisterSourceOutput(blocks, static (spc, items) =>
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("// Generated by LibVLCSharp.Core.Generator. Public PascalCase delegate aliases (twins of");
                sb.AppendLine($"// the libvlc_* callback typedefs in {Naming.InteropNamespace}) with C#-friendly names.");
                sb.AppendLine("// Signatures are identical to the interop twins; convert with a method group at the");
                sb.AppendLine("// P/Invoke boundary. Do not edit.");
                sb.AppendLine();
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine($"using {Naming.InteropNamespace};");
                sb.AppendLine();
                sb.AppendLine($"namespace {Naming.AliasNamespace}");
                sb.AppendLine("{");
                // Stable order independent of syntax-tree visitation order.
                foreach (var block in items.OrderBy(b => b, StringComparer.Ordinal))
                    sb.Append(block);
                sb.AppendLine("}");

                spc.AddSource("LibVLC.Delegates.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            });
        }

        private static string RenderDelegate(DelegateDeclarationSyntax d)
        {
            string snake = d.Identifier.Text;
            string name = DelegateName(snake);
            string modifiers = d.Modifiers.ToString();    // "public unsafe" or "public"
            string returnType = d.ReturnType.ToString();
            string parameters = d.ParameterList.ToString(); // includes parens + per-parameter attributes

            var sb = new StringBuilder();
            sb.AppendLine($"    /// <summary>PascalCase alias of <see cref=\"global::{Naming.InteropNamespace}.{snake}\"/>.</summary>");
            // Copy every attribute list verbatim: [UnmanagedFunctionPointer(...)] and any
            // [return: MarshalAs(...)] the post-process added for _Bool returns.
            foreach (var attr in d.AttributeLists)
                sb.AppendLine($"    {attr}");
            sb.AppendLine($"    {modifiers} delegate {returnType} {name}{parameters};");
            sb.AppendLine();
            return sb.ToString();
        }

        /// <summary>
        /// Maps a <c>libvlc_*</c> callback typedef to a C# delegate name: strips the <c>libvlc_</c>
        /// prefix, renders a <c>_cb</c>/<c>_cbs</c> suffix as <c>Callback</c>/<c>Callbacks</c>, drops
        /// a trailing <c>_t</c>, then PascalCases. e.g. <c>libvlc_video_lock_cb</c> -&gt;
        /// <c>VideoLockCallback</c>, <c>libvlc_callback_t</c> -&gt; <c>Callback</c>.
        /// </summary>
        private static string DelegateName(string snake)
        {
            var s = snake;
            if (s.StartsWith("libvlc_", StringComparison.Ordinal)) s = s.Substring("libvlc_".Length);
            if (s.EndsWith("_cbs", StringComparison.Ordinal))
                return Naming.Pascal(s.Substring(0, s.Length - 4)) + "Callbacks";
            if (s.EndsWith("_cb", StringComparison.Ordinal))
                return Naming.Pascal(s.Substring(0, s.Length - 3)) + "Callback";
            if (s.EndsWith("_t", StringComparison.Ordinal))
                s = s.Substring(0, s.Length - 2);
            return Naming.Pascal(s);
        }
    }
}
