using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LibVLCSharp.Core.Generator
{
    /// <summary>
    /// Incremental source generator that emits public PascalCase parallel enums over the raw
    /// snake_case <c>libvlc_*</c> enums in the (untouched) generated interop file.
    /// <para>
    /// e.g. <c>public enum State { Playing = (int)global::...Interop.libvlc_state_t.libvlc_Playing, ... }</c>.
    /// Each member's value is referenced from the interop enum member (no hard-coded numbers =&gt;
    /// no drift). Replaces the offline <c>tools/AliasGen</c> console step.
    /// </para>
    /// </summary>
    [Generator(Microsoft.CodeAnalysis.LanguageNames.CSharp)]
    public sealed class EnumAliasGenerator : IIncrementalGenerator
    {
        private const string AliasNamespace = "LibVLCSharp.Core";
        private const string InteropNamespace = "LibVLCSharp.Core.Interop";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Each matching interop enum is turned into a self-contained text block (strings are
            // value-equatable, so the incremental pipeline caches correctly).
            var blocks = context.SyntaxProvider.CreateSyntaxProvider(
                    predicate: static (node, _) =>
                        node is EnumDeclarationSyntax e &&
                        e.Identifier.Text.StartsWith("libvlc_", StringComparison.Ordinal),
                    transform: static (ctx, _) => RenderEnum((EnumDeclarationSyntax)ctx.Node))
                .Collect();

            context.RegisterSourceOutput(blocks, static (spc, items) =>
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("// Generated by LibVLCSharp.Core.Generator. Public PascalCase enum aliases over the");
                sb.AppendLine($"// raw snake_case enums in {InteropNamespace}. Values are referenced from the interop");
                sb.AppendLine("// enum members, so they never drift. Do not edit.");
                sb.AppendLine();
                sb.AppendLine($"namespace {AliasNamespace}");
                sb.AppendLine("{");
                // Stable order independent of syntax-tree visitation order.
                foreach (var block in items.OrderBy(b => b, StringComparer.Ordinal))
                    sb.Append(block);
                sb.AppendLine("}");

                spc.AddSource("LibVLC.Enums.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            });
        }

        private static string RenderEnum(EnumDeclarationSyntax e)
        {
            string snakeType = e.Identifier.Text;
            string pascalType = TypeName(snakeType);
            string underlying = e.BaseList?.Types.FirstOrDefault()?.Type.ToString() ?? "int";
            bool isFlags = e.AttributeLists.SelectMany(a => a.Attributes)
                .Any(a => a.Name.ToString() is "Flags" or "FlagsAttribute");

            var members = e.Members.Select(m => m.Identifier.Text).ToList();
            int skip = SkipEnumSegment(snakeType, members);

            var sb = new StringBuilder();
            sb.AppendLine($"    /// <summary>PascalCase alias of <see cref=\"global::{InteropNamespace}.{snakeType}\"/>.</summary>");
            if (isFlags) sb.AppendLine("    [global::System.Flags]");
            sb.AppendLine($"    public enum {pascalType} : {underlying}");
            sb.AppendLine("    {");
            var used = new HashSet<string>(StringComparer.Ordinal);
            foreach (var member in members)
            {
                string name = MemberName(member, skip);
                if (!used.Add(name))
                {
                    // collision after prefix-stripping: fall back to the full member name
                    var alt = MemberName(member, 0);
                    if (!used.Add(alt)) continue;
                    name = alt;
                }
                sb.AppendLine($"        {name} = ({underlying})global::{InteropNamespace}.{snakeType}.{member},");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
            return sb.ToString();
        }

        // --- naming helpers (ported verbatim from tools/AliasGen) ---

        private static string TypeName(string snake)
        {
            var s = snake;
            if (s.StartsWith("libvlc_", StringComparison.Ordinal)) s = s.Substring("libvlc_".Length);
            if (s.EndsWith("_t", StringComparison.Ordinal) || s.EndsWith("_e", StringComparison.Ordinal))
                s = s.Substring(0, s.Length - 2);
            return Naming.Pascal(s);
        }

        private static string MemberName(string member, int skip)
        {
            var segs = member.Split(new[] { '_' }, StringSplitOptions.RemoveEmptyEntries);
            return Naming.Pascal(string.Join("_", segs.Skip(skip)));
        }

        private static int SkipEnumSegment(string enumName, IEnumerable<string> memberNames)
        {
            var enumSegs = StripSuffix(enumName).Split(new[] { '_' }, StringSplitOptions.RemoveEmptyEntries);
            int skip = int.MaxValue;
            foreach (var member in memberNames)
            {
                var memberSegs = member.Split(new[] { '_' }, StringSplitOptions.RemoveEmptyEntries);
                int same = enumSegs.Zip(memberSegs, (a, b) => string.Equals(a, b, StringComparison.OrdinalIgnoreCase))
                    .TakeWhile(x => x).Count();
                // if the first differing segment starts with a digit, keep it (don't strip into a number)
                if (same > 0 && same < memberSegs.Length && memberSegs[same].Length > 0 && char.IsDigit(memberSegs[same][0]))
                    same--;
                if (same < skip) skip = same;
            }
            return skip == int.MaxValue ? 0 : skip;
        }

        private static string StripSuffix(string s)
        {
            if (s.EndsWith("_t", StringComparison.Ordinal) || s.EndsWith("_e", StringComparison.Ordinal))
                return s.Substring(0, s.Length - 2);
            return s;
        }
    }
}
